### ISSUE TITLE
In WebViewJavascriptBridge, there is no way to remove a handler

### ISSUE THREAD

**Issue by oveddan** [marcuswestin/WebViewJavascriptBridge#118]
In the WebViewJavascriptBridge, you should be able to remove a registered handler, in particular:
a) To avoid memory leaks
b) To unsubscribe

(I can work on this)

**Comment by marcuswestin** [comment]
Sure!

I suggest `registerHandler` returns a value (possibly an opaque `id` value) which can later be used to remove the registered handler:

```
    id handlerId = [_bridge registerHandler:@"testObjcCallback" handler:^(id data, WVJBResponseCallback responseCallback) {}];
    ...
    [_bridge removeHandler:handlerId];
```

**Comment by marcuswestin** [comment]
@oveddan: I would still accept a PR for this :)

**Comment by kaunteya** [comment]
Any updates on this?

**Comment by marcuswestin** [comment]
Also see #216
