### ISSUE TITLE
In the Javascript bridge, when there is no handler with the called handler name, provide a better error message.

### ISSUE THREAD

**Issue by oveddan** [marcuswestin/WebViewJavascriptBridge#120]
In the javascript bridge, right now, if you don't have a registered handler for a handlerName, and that handler is called from ios, you get an error message:

> TypeError: undefined is not a function (evaluating 'handler(message.data, responseCallback)')

It would be great if you were given a better error message saying "No handler is registered for handlerName #{handlerName}"

**Comment by marcuswestin** [comment]
As long as it throws an error, I would accept a PR like that.
