### ISSUE TITLE
Passing JS callback function from WebView A to WebView B through Bridge

### ISSUE THREAD

**Issue by mjw56** [marcuswestin/WebViewJavascriptBridge#121]
Hi,

First, thanks for this project.

Second, I have more of a general question of "can this be done using this bridge". Apologies in advance if this is not the right place to ask.

Say I have two different WebViews A and B. I would like to use the bridge to pass a JS callback function from A to B. B can then store the JS callback and fire it at any time and it will hit back to the origination on A's WebView.

Does this sound like something that can be done? If not, do you or anyone have any recommendations on how to achieve this? I appreciate any insight.

**Comment by marcuswestin** [comment]
Every message sent over WebViewJavascriptBridge gets JSON encoded. Since
there is no way to JSON encode a function, you can't send one over the
bridge.

It would be easier to understand what you want to accomplish if you include
example code.

Cheers,
Marcus

**Comment by mjw56** [comment]
Say I have some listening code on WebView A:

```javascript
    PlansActions.prototype.addIOSListeners = function (bridge) {
        var _this = this;
        bridge.init();
        bridge.registerHandler('SUBSCRIBE:PlansStore', function (data, responseCallback) {
            log('Bridge Handler is storing iOS callback with Plans Store', responseCallback);
            Dispatcher.dispatch({
                type: 'SUBSCRIBE_PLANS_STORE',
                callback: responseCallback
            });
        });
    };
```

Now, in WebView B I have a component there who wants to talk to WebView A, specifically to get inside the ``` 'SUBSCRIBE:PlansStore' ``` handler on WebView A.

To start the communication in WebView B I create a wrapper around .callHandler and pass in the handlerName and callback:

```javascript
this.BridgeService.subscribeToStore('Plans', this.updatePlans.bind(this));

BridgeService.prototype.subscribeToStore = function (storeName, callback) {
  var handler = 'SUBSCRIBE:' + storeName + 'Store';
  if (this._bridge)
    this._bridge.callHandler(handler, callback);
  else
    this._queue.push({ type: 'subscribe', handler: handler, callback: callback });
};
```

Now this is where it breaks down a little for me, admittedly my ObjC knowledge is not the greatest...

In ObjC I listen for the callHandler from WebView B and then I'd like to take a callback function that WebView B passes and call from Bridge to JS with it and store it in WebView A so WebView A can call it back at a later date. Something that could theoretically look like this?

```ObjectiveC
    [_bridge registerHandler:@"SUBSCRIBE:PlansStore" handler:^(id data, WVJBResponseCallback responseCallback) {
        NSLog(@"Heard that you want to subscribe to plans store: %@", responseCallback);
        
        [_bridge callHandler:@"SUBSCRIBE:PlansStore" data:nil responseCallback: responseCallback];
    }];
```

I can get as far as seeing that I have heard from WebView B in ObjC. After seeing your response, I guess will probably have to think of another way to solve this?

**Comment by mjw56** [comment]
So I went about it a little differently, but I think it solves my problem. Basically I added a new handler that will be called for change events. Then, WebView B can register for this handler and the callback can be stored there. WebView A calls the handler when something changes, B hears it, and calls the callback. This way don't need to pass callbacks.

Cheers!

**Comment by marcuswestin** [comment]
Sounds like you solved your problem, yes?


Good stuff! Cheers :)


-- while mobile

**Comment by mjw56** [comment]
Yes. I'll close this. 

Thanks for your responses! :)
