### ISSUE TITLE
Support WKWebView in iOS8?

### ISSUE THREAD

**Issue by chipbk10** [marcuswestin/WebViewJavascriptBridge#126]
I've read https://github.com/marcuswestin/WebViewJavascriptBridge/issues/84
and don't know whether you are going to support WKWebView in iOS8 or not? I really appreciate if you support WKWebView. :)

**Comment by lokimeyburg** [comment]
I just want to add that personally I'm not using WKWebView in production because it has too many bugs. I'm not convinced it's ready.

**Comment by chipbk10** [comment]
Another thing is I want to load the local resource. WKWebView for now cannot load the local resource. Is it possible for FLWebView to make it work? :)

**Comment by marcuswestin** [comment]
@chipbk10 check out github.com/marcuswestin/WebViewProxy - it will let you intercept requests for e.g images and then e.g serve them from the local file system if you choose.



-- while mobile

**Comment by chipbk10** [comment]
@marcuswestin: What are you talking about? My problem is I have a html resources downloaded from the server. I want to load it on WKWebView. I use FLWebView for backward compatibility and follow this tutorial :http://stackoverflow.com/questions/24882834/wkwebview-not-working-in-ios-8-beta-4

But still cannot load everything from www folder in Temporary path. The WKWebView cannot load external resources like javascript, xml files.

**Comment by marcuswestin** [comment]
Got it, my bad - I must have misunderstood your need.




Cheers



-- while mobile

**Comment by luowei** [comment]
Looking forward update for support WKWebView...

**Comment by xwv** [comment]
@luowei , @chipbk10, if you still have interesting on JavaScript bridge which supports WKWebView, I'd like to invite you the take a look at the [XWebView](https://github.com/xwebview/xwebview) project.

**Comment by marcuswestin** [comment]
This is done since a while back :)

Use 4.1.5 for WKWebView support.

You should also consider switching to v5.0.1. If you do, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage.

Cheers!
