### ISSUE TITLE
if I try to use bridge in $(document).ready, undefined error occur

### ISSUE THREAD

**Issue by nicecue** [marcuswestin/WebViewJavascriptBridge#131]

**Comment by marcuswestin** [comment]
Hi @nicecue,

Please read https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/README.md#usage.

In particular, note that you must use `setupWebViewJavascriptBridge(function(bridge) { ... })` and can't use the `bridge` before that callback is called.

Cheers!
