### ISSUE TITLE
Memory leaks？

### ISSUE THREAD

**Issue by cyqluowang** [marcuswestin/WebViewJavascriptBridge#135]
maybe Memory leaks？idont know。
i use like this,but it not call.

**Comment by cyqluowang** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/5178594/8889860/4c9914c8-331e-11e5-8b81-1535593da4b2.png)
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/5178594/8889861/4ca2642e-331e-11e5-9777-290b2ec065ff.png)

**Comment by cyqluowang** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/5178594/8889868/77d6fa2e-331e-11e5-843a-728982175ec3.png)
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/5178594/8889867/77d68058-331e-11e5-876b-ea72bc26dcee.png)
![1](https://cloud.githubusercontent.com/assets/5178594/8889872/9e54c078-331e-11e5-8694-8f38eeafd73c.png)

**Comment by cyqluowang** [comment]
#62

**Comment by cyqluowang** [comment]
ok ，i know the problem .sorry

**Comment by marcuswestin** [comment]
Cheers :)
