### ISSUE TITLE
New release and cocoaPods update

### ISSUE THREAD

**Issue by josephyzhou** [marcuswestin/WebViewJavascriptBridge#143]
Hi Marcus,
First of all, thanks a lot for this!
Are you planning on doing a new release/update cocoaPods soon? I'm using swift and cocoaPods does make my life a little easier :)

**Comment by marcuswestin** [comment]
Hi Joseph, thanks for the kind words :)

Try 4.1.5. You may also want to check out the new version, v5.0.1. If you do, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

Cheers!
