### ISSUE TITLE
Never call -(void)dealloc?

### ISSUE THREAD

**Issue by KittenYang** [marcuswestin/WebViewJavascriptBridge#144]
Here it is:

![2015-08-21 1 25 34](https://cloud.githubusercontent.com/assets/5517281/9401873/6aafacca-4808-11e5-9435-94522daed398.png)

It shows this line ` [strongWebView stringByEvaluatingJavaScriptFromString:javascriptCommand];` use much memory.

Besides,if I connect UIWebView to bridge like:
```
    _bridge = [WebViewJavascriptBridge bridgeForWebView:_webView webViewDelegate:self handler:^(id data, WVJBResponseCallback responseCallback) {
        
    }];

```

it'll never call -(void)dealloc

but if I remove those code ,it will.
Do you know what's wrong with it? Thanks.

**Comment by yirenjun** [comment]
Your js call native handler that not exist ？

see pull request #179
