### ISSUE TITLE
when webview load data from memory, 

### ISSUE THREAD

**Issue by Serlight** [marcuswestin/WebViewJavascriptBridge#147]
NSString *dataStr = @"<!doctype html> \
    <html><head> \
    <meta name='viewport' content='user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0'> \
    <style type='text/css'> \
    html { font-family:Helvetica; color:#222; } \
    h1 { color:steelblue; font-size:24px; margin-top:24px; } \
    button { margin:0 3px 10px; font-size:12px; } \
    .logLine { border-bottom:1px solid #ccc; padding:4px 2px; font-family:courier; font-size:11px; } \
    </style> \
    </head><body> \
    <h1>WebViewJavascriptBridge Demo</h1> \
    <script> \
    window.onerror = function(err) { \
    log('window.onerror: ' + err) \
    } \
    function connectWebViewJavascriptBridge(callback) { \
    if (window.WebViewJavascriptBridge) { \
    callback(WebViewJavascriptBridge) \
    } else { \
    document.addEventListener('WebViewJavascriptBridgeReady', function() { \
				callback(WebViewJavascriptBridge) \
    }, false) \
    } \
    } \
    connectWebViewJavascriptBridge(function(bridge) { \
    var uniqueId = 1 \
    function log(message, data) { \
    var log = document.getElementById('log') \
    var el = document.createElement('div') \
    el.className = 'logLine' \
    el.innerHTML = uniqueId++ + '. ' + message + ':<br/>' + JSON.stringify(data) \
    if (log.children.length) { log.insertBefore(el, log.children[0]) } \
    else { log.appendChild(el) } \
    } \
    bridge.init(function(message, responseCallback) { \
    log('JS got a message', message) \
    var data = { 'Javascript Responds':'Wee!' } \
    log('JS responding with', data) \
    responseCallback(data) \
    }) \
    bridge.registerHandler('testJavascriptHandler', function(data, responseCallback) { \
    log('ObjC called testJavascriptHandler with', data) \
    var responseData = { 'Javascript Says':'Right back atcha!' } \
    log('JS responding with', responseData) \
    responseCallback(responseData) \
    }) \
    var button = document.getElementById('buttons').appendChild(document.createElement('button')) \
    button.innerHTML = 'Send message to ObjC' \
    button.onclick = function(e) { \
    e.preventDefault() \
    var data = 'Hello from JS button' \
    log('JS sending message', data) \
    bridge.send(data, function(responseData) { \
				log('JS got response', responseData) \
    }) \
    } \
    document.body.appendChild(document.createElement('br')) \
    var callbackButton = document.getElementById('buttons').appendChild(document.createElement('button')) \
    callbackButton.innerHTML = 'Fire testObjcCallback' \
    callbackButton.onclick = function(e) { \
    e.preventDefault() \
    log('JS calling handler') \
    bridge.callHandler('testObjcCallback', {'foo': 'bar'}, function(response) { \
				log('JS got response', response) \
    }) \
    } \
    }) \
    </script> \
    <div id='buttons'></div> <div id='log'></div> \
    </body></html> ";
    
    [webView loadHTMLString:dataStr baseURL:nil];

i load data like top. but the js not run, how can i do it

**Comment by marcuswestin** [comment]
I can't help without more information. What's the difference between the example apps and your code?

Feel free to reopen with enough information to reproduce your problem.

Cheers!

**Comment by Serlight** [comment]
@marcuswestin, sorry for not reply quickly. i fixed it, when load local html resource, we must use local base url
