### ISSUE TITLE
Small help with Swift setup

### ISSUE THREAD

**Issue by DarkoKulakov** [marcuswestin/WebViewJavascriptBridge#148]
Hi, I need help setting the WebViewJavascriptBridge under Swift. I imported the folder, made the bridged header, but I can not receive the callback for the registered handler. Here is the code I use

        
        self.bridge = WebViewJavascriptBridge(forWebView: self.uiWebView, webViewDelegate: self) { [unowned self](data, responseCallback) -> Void in
            
            if let dataObj = data as? Dictionary<String, String> {
                println(dataObj)
            }
        }
        
        self.bridge.registerHandler("articleInlineOpened") { [unowned self](data, responseCallback) -> Void in
            if let dataObj = data as? Dictionary<String, String> {
                println(dataObj)
            }
        }
    
With the logging enabled, I can see that the web page is invoking the callback, but it never enters in the completion block. And there is error message logged.

 WVJB RCVD: {"handlerName":"inlineArticleOpened"}
 *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <WVJBNoHandlerException> No handler for message from JS: <CFBasicHash 0x170669980 [0x197948f50]>{type = immutable dict, count = 1,
entries =>
	1 : <CFString 0x170622c60 [0x197948f50]>{contents = "handlerName"} = <CFString 0x1704449b0 [0x197948f50]>{contents = "inlineArticleOpened"}
}

If there is some example in Swift, or some one can help me I would be really grateful.

**Comment by marcuswestin** [comment]
What was the answer? :)

**Comment by DarkoKulakov** [comment]
There was no real answer, after reading the documentation I found that we
were not handling the request properly. Delete it as it is not an issue.

Thanks
