### ISSUE TITLE
podspec doesn't include WKWebView support

### ISSUE THREAD

**Issue by ExoticObjects** [marcuswestin/WebViewJavascriptBridge#149]
Maybe that's intentional? In case it's an oversight, posting this...

**Comment by marcuswestin** [comment]
@ExoticObjects: How do I note that WVJB supports WKWebView in the podspec file?

A PR would be great!

**Comment by ExoticObjects** [comment]
Actually, I guess it wouldn't show up in the podspec. But it looks like you added support for WKWebView after this comment? [See here](https://github.com/marcuswestin/WebViewJavascriptBridge/commit/0e64a1782b27f9c6e94989089a3cd03ba33f1c99)...
 At any rate, it's supported now, so closing...
