### ISSUE TITLE
Testing JS in WVJB

### ISSUE THREAD

**Issue by tetriscode** [marcuswestin/WebViewJavascriptBridge#151]
Does anyone know of a way to do CI on the Javascript running against WJVB?

I'd like to do BDD style tests to confirm my mobile js support library which is only meant to use WJVB to communicate. I'm writing a fairly large library that I want the JS to get the benefits of TDD as I develop.

**Comment by marcuswestin** [comment]
See `Tests/*` and https://travis-ci.org/marcuswestin/WebViewJavascriptBridge for automated testing of WVJB.

If you clone this repo you can run the tests locally with `make test`.
