### ISSUE TITLE
WKWebViewJavascriptBridge did not support Swift?

### ISSUE THREAD

**Issue by kmyhy** [marcuswestin/WebViewJavascriptBridge#153]
I used WebViewJavascriptBridge in my Xcode6.4 project(Swift),it is ok.
But when I tried to import WKWebViewJavascriptBridge in the same project,I got that compiler error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WKWebViewJavascriptBridge", referenced from:
      __TMaCSo25WKWebViewJavascriptBridge in WKWebViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ahallora** [comment]
I have the same issue. It works for UIWebView but WKWebView throws said error... :(

**Comment by dwieringa** [comment]
I'm seeing the same error on an Objective-C project in Xcode 7.0.1.  I was using WebViewJavascriptBridge fine with UIWebView, but when I tried to switch to WKWebViewJavascriptBridge for WKWebView, I started seeing this linker error.

**Comment by rexpie** [comment]
Same issue here. Is there a workaround?

**Comment by dwieringa** [comment]
@rexpie I needed to move on and was able to drop iOS 7 support, so I personally switched to just using WKScriptMessage/WKScriptMessageHandler.

**Comment by rexpie** [comment]
@dwieringa Okay thanks for that.
Hey I just worked out a way to get this right. 

In file `WKWebViewJavascriptBridge.h`, find these lines:

    #if (__MAC_OS_X_VERSION_MAX_ALLOWED > __MAC_10_9 || __IPHONE_OS_VERSION_MAX_ALLOWED > __IPHONE_7_1)
    #define supportsWKWebKit
    #endif

Then remove the `#if #endif` pair, just leave the `#define supportsWKWebKit` bit out. But *make sure you are using iphone 7.1 or above or it won't support WKWebkit*.

**Comment by marcuswestin** [comment]
Hey guys,

`WKWebView` is only available in iOS 8 and later (https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/).

I believe the problem you're seeing is due to attempting to use WKWebViewJavascriptBridge.h in iOS 7 when you should be using WebViewJavascriptBridge.h.

Feel free to reopen if you think I got it wrong.

Cheers!

**Comment by marcuswestin** [comment]
See https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Example%20Apps/ExampleSwiftApp-iOS/ExampleSwiftApp-iOSTests/ExampleSwiftApp_iOSTests.swift for working Swift unit tests that demonstrate usage.
