### ISSUE TITLE
webView Height

### ISSUE THREAD

**Issue by moyunmo** [marcuswestin/WebViewJavascriptBridge#161]
I want to put the UIWebView into the  TableViewCell.Could you please tell me how to get the height of the UIWebView when i use the WebViewJavascriptBridge.

**Comment by marcuswestin** [comment]
The height of your UIWebView is decided by your objc code, using e.g `initWithFrame`. If you want to update the height of the UIWebView to match the height of the content loaded inside of the UIWebView, then:
1) google e.g "javascript get height of body" to find out how to measure the height of your content using js,
2) measure the height in js and send a message from javascript to objc using WebViewJavascriptBridge,
3) update the height of the UIWebView in objc.
