### ISSUE TITLE
Cannot convert value of type '(AnyObject, WVJBResponseCallback!) -> Void' to expected argument type 'WVJBHandler!'

### ISSUE THREAD

**Issue by joshuakaleb0424** [marcuswestin/WebViewJavascriptBridge#173]
I'm on this block of code
_bridge = [WKWebViewJavascriptBridge bridgeForWebView:webView webViewDelegate:self handler:^(id data, WVJBResponseCallback responseCallback) {
        NSLog(@"ObjC received message from JS: %@", data);
        responseCallback(@"Response for message from ObjC");
    }];

and converted it to swift code

bridge = WKWebViewJavascriptBridge(forWebView: webView, webViewDelegate: self, handler: {(data: AnyObject, responseCallback: WVJBResponseCallback!) -> Void in
              responseCallback("Response for message from ObjC")
            })

but I am receiving this error

" Cannot convert value of type '(AnyObject, WVJBResponseCallback!) -> Void' to expected argument type 'WVJBHandler!' "

**Comment by Monk428** [comment]
use this:
 bridge.registerHandler("obj") { (data, WVJBResponseCallback) -> Void in   
 }
hope to help you!

**Comment by marcuswestin** [comment]
Please see https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Example%20Apps/ExampleSwiftApp-iOS/ExampleSwiftApp-iOSTests/ExampleSwiftApp_iOSTests.swift for working Swift unit tests that illustrate how to use WebViewJavascriptBridge from Swift.
