### ISSUE TITLE
when the webview evaluete javascript fail will cause crash

### ISSUE THREAD

**Issue by zhipcui** [marcuswestin/WebViewJavascriptBridge#183]
- (void)WKFlushMessageQueue {
    [_webView evaluateJavaScript:[_base webViewJavascriptFetchQueyCommand] completionHandler:^(NSString* result, NSError* error) {
        [_base flushMessageQueue:result];
    }];
}

The reason:
if the result == nil, then flushMessageQueue try to _deserializeMessageJSON a nill object.

**Comment by marcuswestin** [comment]
Fixed in v5.0.2
