### ISSUE TITLE
When i hit my url with javascript function as pasted below it opens a popup on mac saying Image attached

### ISSUE THREAD

**Issue by amit-bst** [marcuswestin/WebViewJavascriptBridge#186]
This is only occurring on Safari and not on chrome.

function setupWebViewJavascriptBridge(callback) {
    if (window.WebViewJavascriptBridge) { return callback(WebViewJavascriptBridge); }
    if (window.WVJBCallbacks) { return window.WVJBCallbacks.push(callback); }
    window.WVJBCallbacks = [callback];
    var WVJBIframe = document.createElement('iframe');
    WVJBIframe.style.display = 'none';
    WVJBIframe.src = 'wvjbscheme://**BRIDGE_LOADED**';
    document.documentElement.appendChild(WVJBIframe);
    setTimeout(function() { document.documentElement.removeChild(WVJBIframe) }, 0)
}
<img width="580" alt="screen shot 2016-02-26 at 4 41 15 pm" src="https://cloud.githubusercontent.com/assets/12594308/13350739/e200bcd6-dca7-11e5-912f-dfe9c7d00aa9.png">

**Comment by aliparlar** [comment]
I tried to put this in try catch but to no avail. My current solution is to check if I am actually in a mobile webview before initializing webview

**Comment by kasperpihl** [comment]
Can you post your current solution please?
Have this issue as well.

**Comment by aliparlar** [comment]
In the app, I add the app name to the user agent of the mobile webview, then I look for it on the webpage to safely assume that the agent is a mobile webview initiated by the app and set a IS_MOBILE_APP variable, I use it to show/hide the webbridge and other nasty stuff.

**Comment by kasperpihl** [comment]
Thanks! I found another way that worked out.
FYI:
In JS:
```
window.initJSBridge = function(){
   setupWebViewJavascriptBridge();
}
```

In Objective C (OSX):
```
[self.webView setFrameLoadDelegate:self];
-(void)webView:(WebView *)sender didFinishLoadForFrame:(WebFrame *)frame{
    [sender stringByEvaluatingJavaScriptFromString:@"if(window.initJSBridge) window.initJSBridge()"];
}
```

**Comment by pospears** [comment]
Can you post your modified JS  setupWebViewJavascriptBridge() function.  I want to see how you handled the callback parameter on initialization.

**Comment by kasperpihl** [comment]
I didn't modify the setupWebViewJavascriptBridge function, didn't need the callback

**Comment by marcuswestin** [comment]
You should not use the WVJB javascript unless it's inside of a WVJB view.
