### ISSUE TITLE
JSContext

### ISSUE THREAD

**Issue by indexjincieryi** [marcuswestin/WebViewJavascriptBridge#189]
I want to know your project and the iOS7.0 out of JSContext what's the difference，Thanks

**Comment by aelam** [comment]
WKWebView won't be able to get the context. 
you will get a lot of troubles if you want to upgrade to WKWebView from UIWebView

**Comment by marcuswestin** [comment]
Not sure I understand the problem here. Feel free to reopen with more info.

**Comment by cjhenck** [comment]
@marcuswestin: If I understand @indexjincieryi, I think that this is a legitimate question to answer on the README. How does your library improve over what is built into JSContext?
