### ISSUE TITLE
No response on first call to native from JS

### ISSUE THREAD

**Issue by maxcampolo** [marcuswestin/WebViewJavascriptBridge#192]
Hello. When first initializing the bridge sometimes the first call to native handlers is not received. My solution so far has been to use "dummy" calls where I call all the handlers once when I initialize before I can call them again to expect a response from native.

This doesn't happen every time, sometimes it works as expected. Is this a behavior that has been seen before?

Thanks for the awesome library.

**Comment by Smeegol** [comment]
@maxcampolo How have you fixed this problem later? We also meet it now.
