### ISSUE TITLE
Missing [super dealloc]

### ISSUE THREAD

**Issue by ddovod** [marcuswestin/WebViewJavascriptBridge#194]
Hello Marcus.
Thank you a lot for this project!
I have some warnings pointing in [(WK)WebViewJavascriptBridge dealloc]. This method should call [super dealloc], but it doesn't. Is there any special case connected with this behavior? Or it is just an issue which should be fixed?
Thank you again!

**Comment by marcuswestin** [comment]
I think it should call super dealloc! Good catch. Can you create a PR?

Thanks!

**Comment by stasnikiforov** [comment]
Maybe I'm missing something but "ARC forbids explicit message send of 'dealloc'" and, therefore, one cannot ever call [super dealloc] if the project is compiled with ARC. The compiler handles it for you implicitly.

**Comment by ddovod** [comment]
@marcuswestin Sure
@stasnikiforov Yes, but in our project we don't use ARC, I'll think about it

**Comment by ddovod** [comment]
In case of how ARC works I think that info about settings and compiler flags would be the best fix for this issue.

**Comment by marcuswestin** [comment]
Fixed in #195
