### ISSUE TITLE
WebViewJavascriptBridge Conflict with NJKWebViewProgress

### ISSUE THREAD

**Issue by qshuangwen** [marcuswestin/WebViewJavascriptBridge#199]
In my project at the same time use the NJKWebViewProgress and WebViewJavascriptBridge the two frameworks, after debugging, found that the two frameworks can't good synergy, can lead to the following method will not be invoked
- (void) webViewProgress: (NJKWebViewProgress *) webViewProgress updateProgress (float) progress;
  I want to how to solve this problem?

**Comment by marcuswestin** [comment]
Not sure. I'd gladly accept a PR with a good solution. Feel free to reopen with more info.
