### ISSUE TITLE
Documentation inconsistency with code (Usage step #3)

### ISSUE THREAD

**Issue by Dev-iL** [marcuswestin/WebViewJavascriptBridge#201]
`README.md` gives the following code in step 3 of the [**Usage**](https://github.com/marcuswestin/WebViewJavascriptBridge#usage) section:

```
...
[self.bridge callHandler:@"JS Echo" responseCallback:^(id responseData) {
    NSLog(@"ObjC received response: %@", responseData);
}];
```

Or in other words:

```
callHandler:(NSString *)handlerName responseCallback:(WVJBResponseCallback)responseCallback{...}
```

However, the `callHandler` variants defined in `WebViewJavascriptBridgeBase.m` are:

```
- (void)callHandler:(NSString *)handlerName {
    [self callHandler:handlerName data:nil responseCallback:nil];
}

- (void)callHandler:(NSString *)handlerName data:(id)data {
    [self callHandler:handlerName data:data responseCallback:nil];
}

- (void)callHandler:(NSString *)handlerName data:(id)data responseCallback:(WVJBResponseCallback)responseCallback {
    [_base sendData:data responseCallback:responseCallback handlerName:handlerName];
}
```

Which results in the error:

```
no visible @interface for 'WebViewJavascriptBridge' declares the selector 'callHandler:responseCallback:'
```

This means the documentation is currently _wrong_. There are two ways to resolve this:
1. Add the mentioned (missing) variant of `callHandler` to `WebViewJavascriptBridgeBase.m`.
2. Update the documentation to use one of the existing variants.

**Comment by marcuswestin** [comment]
Thanks!

**Comment by Dev-iL** [comment]
Np; thank_you_ for making this utility and maintaining it :)
