### ISSUE TITLE
can't run on ios 9.3

### ISSUE THREAD

**Issue by ZhangJunkang** [marcuswestin/WebViewJavascriptBridge#204]
I use this framework on ios 9.3 ，i use JavaScript call oc ,but don't get any information ,and don't ResponseCallback

**Comment by shaohualiang** [comment]
check your JavaScripte code, your function should be coding in  function setupWebViewJavascriptBridge

**Comment by SimpLeYuchao** [comment]
yong pin yin shuo duo hao  , because we are  Singaporean.

**Comment by marcuswestin** [comment]
Try running the example apps. They'll probably work for you. If yes, just trace out what the difference is in your code.

Cheers!
