### ISSUE TITLE
use this lib in swift but can not get anyobject in webview

### ISSUE THREAD

**Issue by yhdaren** [marcuswestin/WebViewJavascriptBridge#209]
please help me ,before use old version webviewjsbrigre. now use old version can not call handle js  .use new version can not get anything

**Comment by yhdaren** [comment]
With the old version (version) with TXT, js method can call the swift, but swift callhandle is invalid.Using the latest version of js tuning up local method, cannot send to js, I can capture

**Comment by marcuswestin** [comment]
How do I repro this? Feel free to reopen with more info.
