### ISSUE TITLE
Can you send me include js. TXT file version of the old demo?thank you very much

### ISSUE THREAD

**Issue by yhdaren** [marcuswestin/WebViewJavascriptBridge#210]
Can you send me include js. TXT file version of the old demo?thank you very much

**Comment by marcuswestin** [comment]
Hi! You can use the github commit history to get that file. (It's what I
would be doing if I were to find it for you).

Cheers!

**Comment by marcuswestin** [comment]
(It's worth noting that you can't use the latest version of wvjb with the
js txt file. You would have to use an old version entirely, rather than
mixing the newest version with that old file)

**Comment by marcuswestin** [comment]
Feel free to reopen with more info.
