### ISSUE TITLE
the data transfer help

### ISSUE THREAD

**Issue by wealon** [marcuswestin/WebViewJavascriptBridge#212]
1. my JS transform data
   bridge.callHandler('testAlertByType', {"type": 1, "title" : "this is title" , "content" : "this is content", "confirm" : "logout"}, function(response) {
                           console.log('Native 给 JS 返回数据 :', response)
                       })
2. objc  receive
   Printing description of params:
   {
   confirm = logout;
   content = "this is content";
   title = "this is title";
   type = 1;
   }

**Comment by wealon** [comment]
if JS pass a string value with white space , OC will get the value with " " ,like the value is  "this is title"   
but   if the  string value without white space , OC will get the value without " "  , like the value is "logout"

thank you

**Comment by wealon** [comment]
![Uploading error.png…]()

**Comment by marcuswestin** [comment]
Sorry, I don't understand the problem here. Looks like expected behavior to me. Reopen with more info if you'd like to.
