### ISSUE TITLE
handler can only handle once 

### ISSUE THREAD

**Issue by aelam** [marcuswestin/WebViewJavascriptBridge#213]
In the OC side. it won't be enable to call twice. 
because
In `_dispatchMessageFromObjC`. the responseId is deleted after responsecallback();
Is it possible to enable it execute to run more than one time? 

in File WebViewJavascriptBridge_JS.m

``` objc
    void (^handler)(id, WVJBResponseCallback) = ^(id data, WVJBResponseCallback responseCallback){
        // First time
        responseCallback(@{JSResponseErrorCodeKey:@(JSResponseErrorCodeSuccess)});
        // The second time, responseCallback mapped responeId has been removed
        responseCallback(@{JSResponseErrorCodeKey:@(JSResponseErrorCodeSuccess)});
    };
```

**Comment by EasonGaoDevelop** [comment]
how to solve this problem

**Comment by aelam** [comment]
@EasonGaoDevelop , let front-side developer calls the function directly rather than call the responseCallback repeatedly.

**Comment by aelam** [comment]
@EasonGaoDevelop ,                  
I use `evaluateJavaScript ` for this requirement. 
```
  [webView evaluateJavaScript:[NSString stringWithFormat:@"%@(%@)",parameters[@"callback"], [payResultInfo jsonString]]];
```

**Comment by EasonGaoDevelop** [comment]
I use registerHandler method ,But when my second call responseCallback , Not implemented
！I found the reason, on WebViewJavascriptBridge.js.txt 
	delete responseCallbacks[message.responseId]

**Comment by marcuswestin** [comment]
This is intentional. If you want to call JS code multiple times, call a registered handler
