### ISSUE TITLE
Register for any handler

### ISSUE THREAD

**Issue by cepages** [marcuswestin/WebViewJavascriptBridge#223]
Hi

I used to use the version 4 where I could do this:

```
self.bridge = [WebViewJavascriptBridge bridgeForWebView:self.webview handler:^(id data, WVJBResponseCallback responseCallback) {
            [self methodToProcessData:Data];
}];
```

Which it used to make me easier because I register for any handle and in the block I process the data.

With the current version I have to duplicate code:

```
        [self.bridge registerHandler:@"bla" handler:^(id data, WVJBResponseCallback responseCallback) {
            ...
            [self methodToProcessData:Data];
        }];
        [self.bridge registerHandler:@"more bla" handler:^(id data, WVJBResponseCallback responseCallback) {
            ...
            [self methodToProcessData:Data];
        }];
```

Can I do it like in the past and get the method called for any call sent? So I will process the data when is sent.

Thanks in advance :)

**Comment by marcuswestin** [comment]
I'd suggest:
- On JS side, create a `sendWildcardData` wrapper function which calls `callHandler('wildcard')`
- On ObjC side, create a `wildcard` handler which calls`[self methodToProcessData:data]`
