### ISSUE TITLE
about callhandle only Execute once

### ISSUE THREAD

**Issue by EasonGaoDevelop** [marcuswestin/WebViewJavascriptBridge#224]
When I use WebViewJavascriptBridge found callback executes only once, debug found is the execution of the delete responseCallbacks[message.responseId] in WebViewJavascriptBridge.js.text I can delete this line of code?

**Comment by zawaliang** [comment]
You can use "+ (instancetype)bridgeForWebView:(WVJB_WEBVIEW_TYPE*)webView webViewDelegate:(WVJB_WEBVIEW_DELEGATE_TYPE*)webViewDelegate handler:(WVJBHandler)messageHandler resourceBundle:(NSBundle*)bundle" method

**Comment by zawaliang** [comment]
@EasonGaoDevelop You can use "+ (instancetype)bridgeForWebView:(WVJB_WEBVIEW_TYPE)webView webViewDelegate:(WVJB_WEBVIEW_DELEGATE_TYPE)webViewDelegate handler:(WVJBHandler)messageHandler resourceBundle:(NSBundle*)bundle" method

**Comment by marcuswestin** [comment]
Dupe of #213
