### ISSUE TITLE
retain cycle

### ISSUE THREAD

**Issue by Damonvvong** [marcuswestin/WebViewJavascriptBridge#225]
- Follow code case retain cycle:

``` objc
@property (nonatomic, strong) WKWebViewJavascriptBridge *bridge;

-(WKWebViewJavascriptBridge *)bridge{
    if (!_bridge) {
        WKWebViewJavascriptBridge *bridge = [WKWebViewJavascriptBridge bridgeForWebView:self.webView];

        [bridge setWebViewDelegate:self];
        _bridge = bridge;
    }
    return _bridge;
}
```
- Is my code wrong or WKWebViewJavascriptBridge has this bug?

**Comment by Henry519** [comment]
I have the same issue.Did you solve the problem?

**Comment by azsuth** [comment]
Also having the same issue. Any updates?

**Comment by azsuth** [comment]
I fixed this by clearing the reference to the bridge when I no longer need it.

**Comment by Damonvvong** [comment]
@Henry519  No yet，I do the same way like @azsuth  said

**Comment by zypsusu** [comment]
- (void)viewWillDisappear:(BOOL)animated{
    [super viewWillDisappear:animated];
    [self.bridge setWebViewDelegate:nil];
    self.bridge = nil;
}
You can do this!

**Comment by XGPASS** [comment]
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    if (self.bridge) {
        [self.bridge setWebViewDelegate:self];
    }
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.bridge setWebViewDelegate:nil];
}
I think it will be better！

**Comment by marcuswestin** [comment]
I believe this has been fixed. Please update to latest version and check. Feel free to reopen.
