### ISSUE TITLE
Get crash on -[WebViewJavascriptBridge dealloc] (WebViewJavascriptBridge.m:94)

### ISSUE THREAD

**Issue by weiminghuaa** [marcuswestin/WebViewJavascriptBridge#227]
Get many crashes on Crash Report Tools. I can't reappear. Someone can help me. Thank you very much.

SIGSEGV
SEGV_ACCERR
0  libobjc.A.dylib 0x0000000197babbd0 objc_msgSend + 16
1  MyApp 0x000000010044b2f4 -[WebViewJavascriptBridge dealloc (WebViewJavascriptBridge.m:94)
2  MyApp 0x00000001000c1314 -[MyWebViewController .cxx_destruct (MyWebViewController.m:49)
3  libobjc.A.dylib 0x0000000197b96b1c object_cxxDestructFromClass(objc_object*, objc_class*) + 148
4  libobjc.A.dylib 0x0000000197ba3f38 objc_destructInstance + 92
5  libobjc.A.dylib 0x0000000197ba3f90 object_dispose + 28
6  UIKit 0x000000018bf70d64 -[UIResponder dealloc] + 116
7  UIKit 0x000000018bdbd98c -[UIViewController dealloc] + 1912
8  MyApp 0x00000001000baa80 -[MyWebViewController dealloc] (MyWebViewController.m:69)
9  MyApp 0x000000010015d7fc -[MyToolsWebViewController dealloc] (MyToolsWebViewController.m:55)

**Comment by unkosun** [comment]
I get the same crash , how to fix it?

**Comment by weiminghuaa** [comment]
I don't konw. I got this crash only in ios8, and no one rely. So I close.
