### ISSUE TITLE
Conflict for NJKWebviewprogress delegate

### ISSUE THREAD

**Issue by wulinfeng198810** [marcuswestin/WebViewJavascriptBridge#228]
_progressProxy = [[NJKWebViewProgress alloc] init];
    _webView.delegate = _progressProxy;
  **_progressProxy.webViewProxyDelegate = self;**
    _progressProxy.progressDelegate = self;

```
CGFloat progressBarHeight = 2.f;
CGRect navigationBarBounds = self.navigationController.navigationBar.bounds;
CGRect barFrame = CGRectMake(0, navigationBarBounds.size.height - progressBarHeight, navigationBarBounds.size.width, progressBarHeight);
_progressView = [[NJKWebViewProgressView alloc] initWithFrame:barFrame];
_progressView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;

_webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height - 64)];
[self.view addSubview:_webView];

[WebViewJavascriptBridge enableLogging];

_bridge = [WebViewJavascriptBridge bridgeForWebView:_webView];
**[_bridge setWebViewDelegate:self];**


__weak __typeof(self)weakSelf = self;
[_bridge registerHandler:@"testObjcCallback" handler:^(id data, WVJBResponseCallback responseCallback) {
    [weakSelf downloadAttachments:data];
}];

[_bridge callHandler:@"testJavascriptHandler" data:@{ @"url":@"http:www.baidu.com" }];
```

Question:
_progressProxy.webViewProxyDelegate = self;
[_bridge setWebViewDelegate:self];

The delegate will take over behind the front of the delegate?  
How to deal with it?

**Comment by wulinfeng198810** [comment]
_webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height - 64)];
[self.view addSubview:_webView];

[WebViewJavascriptBridge enableLogging];

_bridge = [WebViewJavascriptBridge bridgeForWebView:_webView];
**[_bridge setWebViewDelegate:self];**


__weak __typeof(self)weakSelf = self;
[_bridge registerHandler:@"testObjcCallback" handler:^(id data, WVJBResponseCallback responseCallback) {
    [weakSelf downloadAttachments:data];
}];

[_bridge callHandler:@"testJavascriptHandler" data:@{ @"url":@"http:www.baidu.com" }];

_progressProxy = [[NJKWebViewProgress alloc] init];
_webView.delegate = _progressProxy;
**_progressProxy.webViewProxyDelegate = _bridge;**
_progressProxy.progressDelegate = self;

CGFloat progressBarHeight = 2.f;
CGRect navigationBarBounds = self.navigationController.navigationBar.bounds;
CGRect barFrame = CGRectMake(0, navigationBarBounds.size.height - progressBarHeight, navigationBarBounds.size.width, progressBarHeight);
_progressView = [[NJKWebViewProgressView alloc] initWithFrame:barFrame];
_progressView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;

**Comment by wulinfeng198810** [comment]
这样就解决了

**Comment by marcuswestin** [comment]
Looks like there's a suggested solution. Feel free to reopen with more info.

**Comment by khalilleo** [comment]
用您的方法似乎解决了问题，但是_progressProxy好像直接不显示了

The solution seems working, but the _progressProxy seems broken and disappeared
