### ISSUE TITLE
unregisterHandler in JS

### ISSUE THREAD

**Issue by igabesz** [marcuswestin/WebViewJavascriptBridge#234]
We would like to use this app with dynamic subscriptions. Thus we need an `unregisterHandler` function, similar to `registerHandler`. Is this possible? 

For example: 

``` javascript
let handlerId = bridge.registerHandler('event-name', (data) => { /* ... */ })
bridge.unregisterHandler(handlerId);
```

**Comment by marcuswestin** [comment]
Would accept a good pr

**Comment by marcuswestin** [comment]
Also see #216

**Comment by marcuswestin** [comment]
Dupe of #118
