### ISSUE TITLE
- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler

### ISSUE THREAD

**Issue by Oxidosnel** [marcuswestin/WebViewJavascriptBridge#235]
- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler

//这个函数处理有问题，
    if (webView != _webView) {
      //需要加上下面这个
      completionHandler(0,nil); 
      return; 
}

```
__strong typeof(_webViewDelegate) strongDelegate = _webViewDelegate;
if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:didReceiveAuthenticationChallenge:completionHandler:)]) {
    [strongDelegate webView:webView didReceiveAuthenticationChallenge:challenge completionHandler:completionHandler];
}
```

//需要加上下面这个
else{
        completionHandler(0,nil);
    }

**Comment by Oxidosnel** [comment]
可恶的崩溃

**Comment by blueseaguo** [comment]
HZ,我也遇到这个问题，为啥会crash

**Comment by marcuswestin** [comment]
I think might work after 9c1e39200d9a3fdc4437b7a4897d5c7f1212dd36 (#218). Feel free to reopen with more info.

**Comment by monkerek** [comment]
@marcuswestin I think the completionHandler is still expected to be invoked if (webView != _webView) happens

**Comment by marcuswestin** [comment]
What's the situation when that could happen?

**Comment by monkerek** [comment]
@marcuswestin isn't it just whenever (webView != _webView) happens? if we want to guard against that condition we should still invoke the completion block and pass error result back to the caller. simply put, currently if this code block gets triggered it crashes
