### ISSUE TITLE
data parameter is nil crash

### ISSUE THREAD

**Issue by XJShane** [marcuswestin/WebViewJavascriptBridge#236]
- (NSArray*)_deserializeMessageJSON:(NSString *)messageJSON {
  return [NSJSONSerialization JSONObjectWithData:[messageJSON dataUsingEncoding:NSUTF8StringEncoding] options:NSJSONReadingAllowFragments error:nil];
  }

when messageJSON is nil,it will crash.

error infomaiton: 'NSInvalidArgumentException', reason: 'data parameter is nil'.

**Comment by marcuswestin** [comment]
Can't help without instructions for how to repro. Feel free to reopen with more info.
