### ISSUE TITLE
iphone6s. ios10. wkwebview. crash！！！

### ISSUE THREAD

**Issue by fandudu** [marcuswestin/WebViewJavascriptBridge#240]
somebody can compatible？

**Comment by zacard-orc** [comment]
+1,same probelm

**Comment by kaunteya** [comment]
+1.
I tried creating a sample app wherein I just added a `WKWebView` and implemented `WKScriptMessageHandler`. I am getting the same error.
The exact same code works in iOS 9.*

**Comment by sunwell** [comment]
Maybe it is a WKWebView's unknown bug.
ps: Please give your error information.

**Comment by marcuswestin** [comment]
If you open the ExampleApp and run that, does it work?

**Comment by huangshun11** [comment]
If load local html success
plz load "www.baidu.com" crash!

**Comment by huangshun11** [comment]
can not load "http:// " !!!

**Comment by marcuswestin** [comment]
Hey guys,

All the WKWebViewJavascriptBridge tests are passing. If you want help with this, please follow the issue reporting instructions and create a PR with a failing test case:

https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/.github/ISSUE_TEMPLATE.md

Cheers!
Marcus

**Comment by marcuswestin** [comment]
@kaunteya It sounds like you guys are interacting with WKWebView directly, via WKScriptMessageHandler, instead of using WebViewJavascriptBridge.

Since all the tests are currently passing on iPhone 6S iOS10 I'll close this for now. Feel free to reopen with more info or a failing test case!

Cheers
