### ISSUE TITLE
strong cycle

### ISSUE THREAD

**Issue by panghaijiao** [marcuswestin/WebViewJavascriptBridge#243]
@implementation WKWebViewJavascriptBridge {
    WKWebView* _webView;
    id<WKNavigationDelegate> _webViewDelegate;
    long _uniqueId;
    WebViewJavascriptBridgeBase *_base;
}

- (void)setWebViewDelegate:(id<WKNavigationDelegate>)webViewDelegate {
    _webViewDelegate = webViewDelegate;
}

============================================================

id<WKNavigationDelegate> _webViewDelegate == __strong  id<WKNavigationDelegate> _webViewDelegate;

**Comment by marcuswestin** [comment]
I believe this has been fixed. Please update to latest version and check. Feel free to reopen.
