### ISSUE TITLE
import in Objective C bridge file not working

### ISSUE THREAD

**Issue by kaunteya** [marcuswestin/WebViewJavascriptBridge#244]
I have a Swift 3 project.

As mentioned [here](http://stackoverflow.com/a/26895073/1311902]) I have added
```
#import "WebViewJavascriptBridge.h"
```
to Objective C header file, but I am getting error `WebViewJavascriptBridge.h file not found`
I have integrated the framework by pod and testing on iOS 10

**Comment by marcuswestin** [comment]
Please see https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Example%20Apps/ExampleSwiftApp-iOS/ExampleSwiftApp-iOSTests/ExampleSwiftApp_iOSTests.swift for working Swift unit tests that illustrate how to use WebViewJavascriptBridge from Swift.
