### ISSUE TITLE
Is this library compatible with Swift 3 ?

### ISSUE THREAD

**Issue by parvezq** [marcuswestin/WebViewJavascriptBridge#245]
Till swift 2.3, this library seems working perfectly well but its registerHandler method's callback block is not getting executed which seems to work fine earlier in Swift 2.3. 

Below code snippet is from Swift 2.3:
`wkBridge?.registerHandler("handlerName", handler: { (data: AnyObject!, responseCallback: WVJBResponseCallback!) in
            print("Inside java Script handler.")
   })`

Below code snippet is from Swift 3.0 which is not working:
`wkBridge?.registerHandler("handlerName", handler: { (data, responseCallback) in
            print("Inside java Script handler.")
   })`

In swift 3, the "id" data type from Objective c is being mapped to "Any" data type. Why the callback is not being fired ? How to resolve this issue ?

**Comment by mribeiro** [comment]
Did you find a solution for this already?

**Comment by marcuswestin** [comment]
Please see https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Example%20Apps/ExampleSwiftApp-iOS/ExampleSwiftApp-iOSTests/ExampleSwiftApp_iOSTests.swift for working Swift unit tests that illustrate how to use WebViewJavascriptBridge from Swift.
