### ISSUE TITLE
In iOS, how to get data returned NSData type？

### ISSUE THREAD

**Issue by ioslinhao** [marcuswestin/WebViewJavascriptBridge#248]
In iOS:
        [self.brige registerHandler:@"addGoodsFavorite" handler:^(id data, WVJBResponseCallback       responseCallback) {
                NSLog(@"the data class :%@", data.class);
        }];

Results: it is NSDictionary type, how can I get NSData return data type.
For example, data.class  = NSData.

**Comment by marcuswestin** [comment]
NSData represents arbitrary binary data. WebViewJavascriptBridge passes ObjC and JS values (dicts, arrays, numbers and strings). It doesn't make sense for data to be NSData.

If you want to turn `id data` into NSData, choose a way to encode it (e.g JSON), and then do that.

Cheers!

**Comment by ioslinhao** [comment]
thank you，i solved this the issue！I have modified the code，and got a string in the callback。

发自我的 iPhone
