### ISSUE TITLE
Add an universal header makes same code working 

### ISSUE THREAD

**Issue by aelam** [marcuswestin/WebViewJavascriptBridge#249]
Without `use_frameworks!`
we can import it by `#import <WebViewJavascriptBridge/WebViewJavascriptBridge.h>`

but if you turn on `use_frameworks !`
the origin import will be broken. `#import <WebViewJavascriptBridge/WebViewJavascriptBridge.h> `
But if adding a header with same name with framework, and put all headers in it 
Both `#import <WebViewJavascriptBridge/WebViewJavascriptBridge.h> ` and  `@import WebViewJavascriptBridge;` can work

my case is no matter my pod is imported as dynamic framework or static library (by Cocoapods), I don't want the import staff break my code

**Comment by marcuswestin** [comment]
Sounds good! Can you create a PR?

**Comment by marcuswestin** [comment]
Fixed in f3d2aceb5bda
