### ISSUE TITLE
WKWebView retainCycle 

### ISSUE THREAD

**Issue by aelam** [marcuswestin/WebViewJavascriptBridge#251]
Please look at the two parts of code
the two  _webViewDelegate are slightly different 

```
@implementation WKWebViewJavascriptBridge {
    WKWebView* _webView;
    id<WKNavigationDelegate> _webViewDelegate;       // <====== this one is not weak
    long _uniqueId;
    WebViewJavascriptBridgeBase *_base;
}


@implementation WebViewJavascriptBridge {
    WVJB_WEAK WVJB_WEBVIEW_TYPE* _webView;
    WVJB_WEAK id _webViewDelegate;  // <============== here is `weak`
    long _uniqueId;
    WebViewJavascriptBridgeBase *_base;
}

```

**Comment by aelam** [comment]
any updates？

**Comment by aelam** [comment]
#243 
#247
#225
All there might be the same reason

**Comment by maxcampolo** [comment]
This is currently fixed in the master branch. If you are using Cocoapods you will have to point to the master rather than using the latest version.

**Comment by marcuswestin** [comment]
I believe this has been fixed. Please update to latest version and check. Feel free to reopen.
