### ISSUE TITLE
Does WebViewJavascriptBridge safe for passing value?

### ISSUE THREAD

**Issue by yinnieryou** [marcuswestin/WebViewJavascriptBridge#254]
I can pass value to WebViewJavascriptBridge, but does it safe?

Anyone can hack my value?

or what about pass as cookies?

**Comment by marcuswestin** [comment]
Passing values webpage where you control all the the javascript running on that page is safe.

Passing values to a webpage which you don't control or where you are running javascript which you don't control (e.g ads) is not safe.
