### ISSUE TITLE
v5.1.0 bridge cannot work, cause the https request was unknown.

### ISSUE THREAD

**Issue by yanqizhao** [marcuswestin/WebViewJavascriptBridge#257]
I updated to the latest version and loaded my page, received this warning:
WebViewJavascriptBridge: WARNING: Received unknown WebViewJavascriptBridge
If I change the url to http or back to 5.0.5, It does work!

**Comment by marcuswestin** [comment]
Did you get it to work?

**Comment by yanqizhao** [comment]
Yes, I updated to 5.1.2 and it worked, thanks a lot!
