### ISSUE TITLE
WebViewJavascriptBridge  of 6.0.0 version , it can't  response for  iOS.

### ISSUE THREAD

**Issue by x5forever** [marcuswestin/WebViewJavascriptBridge#259]
I found that the WebViewJavascriptBridge of  6.0.0 version can't respond for iOS.I try other version ，and the 5.0.8  version  can't respond for iOS also .

**Comment by VolientDuan** [comment]
I also met this question,can you help me? thx!

**Comment by x5forever** [comment]
@VolientDuan 
You can use the 5.2.0 version for the time being, it can be used normally.

**Comment by qiuzhi199434** [comment]
I'm sorry I can't help you solve this problem




------------------ 原始邮件 ------------------
发件人: "x5forever";<notifications@github.com>;
发送时间: 2017年1月10日(星期二) 下午4:05
收件人: "marcuswestin/WebViewJavascriptBridge"<WebViewJavascriptBridge@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [marcuswestin/WebViewJavascriptBridge] WebViewJavascriptBridge of6.0.0 version , it can't response for iOS. (#259)




@VolientDuan
 You can use the 5.2.0 version for the time being, it can be used normally.

**Comment by VolientDuan** [comment]
ok!thx

**Comment by marcuswestin** [comment]
This should be fixed in v6.0.1 (and 6.0.2) which makes v6 back-compatible with v5
