### ISSUE TITLE
pod 报错了 

### ISSUE THREAD

**Issue by hhb19900618** [marcuswestin/WebViewJavascriptBridge#269]
platform :ios, ‘7.0’
target  ‘ExampleApp-iOS’ do
pod 'WebViewJavascriptBridge', '~> 5.0'
end

报错信息
hhbdeMacBook-Air:Example Apps huhuabin$ pod install
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    project 'path/to/Project.xcodeproj'

**Comment by mathslimin** [comment]
you can change your podfile to this

project 'ExampleApp-iOS.xcodeproj'
target 'ExampleApp-iOS' do
platform :ios, '7.0'
`pod 'WebViewJavascriptBridge', '~> 5.0'`
end
