### ISSUE TITLE
The CocoaPods configuration in README is misleading

### ISSUE THREAD

**Issue by yijiasu** [marcuswestin/WebViewJavascriptBridge#271]
By using this line: `pod 'WebViewJavascriptBridge', '~> 5.0'`
to add WebViewJavascriptBridge to the project, the pod installed the 5.0 version which is unmatched with the `setupWebViewJavascriptBridge` JS snippet provided in README.

It cause ObjC handlers cannot be registered within the setupWebViewJavascriptBridge callback.

Please change the pod config line to use 6.0 version or newer.

**Comment by marcuswestin** [comment]
Fixed. Thank you
