### ISSUE TITLE
App review rejection

### ISSUE THREAD

**Issue by SeongBrave** [marcuswestin/WebViewJavascriptBridge#274]
https://github.com/bang590/JSPatch/issues/746

I Receive the email:

Dear Developer,

Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes.

This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

Best regards,

App Store Review

**Comment by tanis2000** [comment]
That's the standard for the App Store. You can't load code over the web for security reasons

**Comment by yeahdongcn** [comment]
The rejection should not be WebViewJavascriptBridge's problem, my app gets approved last night (it has been rejected twice). I'm currently using `pod 'WebViewJavascriptBridge', '~> 6.0.2'` in my project.

**Comment by PrasadPotale** [comment]
@SeongBrave is your app got approved? 
We are releasing app in next couple of days in which for one screen we are using bridge.

**Comment by marcuswestin** [comment]
WebViewJavascriptBridge is live in hundreds/thousands of app store apps. The problem is very likely in some other part of your code.
