### ISSUE TITLE
Can't find variable: WebViewJavascriptBridge,

### ISSUE THREAD

**Issue by passol1988** [marcuswestin/WebViewJavascriptBridge#277]
> Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: WebViewJavascriptBridge, WKJavaScriptExceptionSourceURL=https://www.fxiaoke.com/fsh5/form/5.4/index.html?fs_nav_fsmenu=false&fs_nav_title=#/forms/172078080536576000?url=https%3A%2F%2Fwww.fxiaoke.com%2Ffsh5%2Fithelpdesk%2F5.4%2Findex.html%3Ffs_nav_fsmenu%3Dfalse%23%2Fresult%3FappId%3DFSAID_1314034&notitle=1, NSLocalizedDescription=发生 JavaScript 异常, WKJavaScriptExceptionColumnNumber=24

this error sometimes occurs,can somebody give me a glue

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!

**Comment by ningshen** [comment]
@passol1988 请问楼主后来有解决方案吗？

**Comment by HelKyle** [comment]
I got the same issue, when i use Sentry to catch errors.
But i can' t reproduce it on my developing environment.
Can someone help?

**Comment by MecDog** [comment]
+1
