### ISSUE TITLE
Completion handler passed to -[WKPrivateNavigationDelegate webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once

### ISSUE THREAD

**Issue by lianweiqin** [marcuswestin/WebViewJavascriptBridge#278]
```
- (void)webView:(WKWebView *)webView
decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
    if (webView != _webView) { return; }
    NSURL *url = navigationAction.request.URL;
    __strong typeof(_webViewDelegate) strongDelegate = _webViewDelegate;

    if ([_base isCorrectProcotocolScheme:url]) {
        if ([_base isBridgeLoadedURL:url]) {
            [_base injectJavascriptFile];
        } else if ([_base isQueueMessageURL:url]) {
            [self WKFlushMessageQueue];
        } else {
            [_base logUnkownMessage:url];
        }
        **decisionHandler(WKNavigationActionPolicyCancel);     //  executed**
    }
    
    if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:decidePolicyForNavigationAction:decisionHandler:)]) {
        **[_webViewDelegate webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];          //  executed** 
    } else {
        decisionHandler(WKNavigationActionPolicyAllow);
    }
}
```

I implement the selector @selector(webView:decidePolicyForNavigationAction:decisionHandler:)
and execute "decisionHandler(WKNavigationActionPolicyAllow);"

It seems the decisionHandler can be called twice and cause the crash.
No such thing has happened before...

**Comment by lokimeyburg** [comment]
(I updated your issue to make your code render in Markdown... makes it easier to read)

Your conditionals allow for more than one handler to be called. Perhaps try and make the statements mutually exclusive?

```
    if ([_base isCorrectProcotocolScheme:url]) {
       // ...
        decisionHandler(WKNavigationActionPolicyCancel);
    } else if (strongDelegate && ... ) {
        [_webViewDelegate webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];
    } else {
        decisionHandler(WKNavigationActionPolicyAllow);
    }
```

**Comment by yudun1989** [comment]
same issue. I met this problem on iOS 11 devices.

**Comment by rollingstoneW** [comment]
if ([_base isCorrectProcotocolScheme:url]) {
       // ...
        decisionHandler(WKNavigationActionPolicyCancel);
        return;
    } else if (strongDelegate && ... ) {
        [_webViewDelegate webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];
    } else {
        decisionHandler(WKNavigationActionPolicyAllow);
    }
It should be this?

**Comment by wunshine** [comment]
got the same problem and not fix yet

**Comment by swifterfit** [comment]
add `return;` . under `        decisionHandler(WKNavigationActionPolicyCancel);
`

**Comment by iPermanent** [comment]
- (void)webView:(WKWebView *)webView
decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
    if (webView != _webView) { return; }
    NSURL *url = navigationAction.request.URL;
    __strong typeof(_webViewDelegate) strongDelegate = _webViewDelegate;

    if ([_base isCorrectProcotocolScheme:url]) {
        if ([_base isBridgeLoadedURL:url]) {
            [_base injectJavascriptFile];
        } else if ([_base isQueueMessageURL:url]) {
            [self WKFlushMessageQueue];
        } else {
            [_base logUnkownMessage:url];
        }
        I disabled this code first
        //decisionHandler(WKNavigationActionPolicyCancel);  
    }
    
    if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:decidePolicyForNavigationAction:decisionHandler:)]) {
       //Here you need to add some code judge if it's the nav by jsbridge then cancel it, 
      if ([[URL.absoluteString lowercaseString] hasPrefix:@"https://__wvjb_queue_message__/"] || [[URL.absoluteString lowercaseString] hasPrefix:@"wvjbscheme://"]) {
            decisionHandler(WKNavigationActionPolicyCancel);
        }else{
            decisionHandler(WKNavigationActionPolicyAllow);
        }
        the code upon is my way to deal it. Hope can help you fix this problem
        [_webViewDelegate webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];          //  executed** 
    } else {
        decisionHandler(WKNavigationActionPolicyAllow);
    }
}

**Comment by iPermanent** [comment]
the code need to be added in your own delegate, and delete the cancel action decisionHandler(WKNavigationActionPolicyCancel); in WKWebViewJavascriptBridge.m

**Comment by pilot34** [comment]
Hm, why this issue is closed? I think, it is not fixed in the last version.

**Comment by iPermanent** [comment]
I think it's duplicate with the others, the same issues has exist already. It's not fixed at all.

**Comment by iosfighterlb** [comment]
Adding 'return'. Can't solve the problem on me.

It seems some sutiation it doesn't enter ： “  if ([_base isWebViewJavascriptBridgeURL:url]) ” 
For example , if you only use WKWebView.

i fix this bug with adding these code in Delegate method: 
```
    WebViewJavascriptBridgeBase *base = [[WebViewJavascriptBridgeBase alloc] init];
    if ([base isWebViewJavascriptBridgeURL:navigationAction.request.URL])
    {
        return;
    }  // Add this IF statement in my project,  don`t need modify WebViewJavascriptBridge`s source code.
       // fixd 'Completion handler passed to -[WKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:...
    decisionHandler(WKNavigationActionPolicyAllow);
```

With these, you can compulsively enter IF and execute return .

**Comment by marcuswestin** [comment]
Fixed in latest release (6.0.3)

**Comment by Dandre126** [comment]
- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler
{
    if (webView != _webView) {
        return;
    }
    NSURL *url = navigationAction.request.URL;
    if ([navigationAction.request.URL.scheme.lowercaseString isEqualToString:@"pingchang"]) {
        if (![self.jsHelper shouldLoadURLRequestWithURL:navigationAction.request.URL]) {
            decisionHandler(WKNavigationActionPolicyCancel);
            return;     // iOS11或xcode9中，此处必须要加一个return，否则就会报上述错误。加了return就可以解决。
        }
    }else if ([url.scheme.lowercaseString isEqualToString:@"http"] ||
              [url.scheme.lowercaseString isEqualToString:@"https"]) {
        _seTipLabel.text = [NSString stringWithFormat:@"此内容由 %@ 提供",url.host];
    }
    
    decisionHandler(WKNavigationActionPolicyAllow);
}

**Comment by iOSQiao** [comment]
Fixed in latest release (6.0.3). 

I don't think this is a good solution. 

It just adds a return.

This will cause the WKWebView to load the page much slower than the UIWebView.

Here's my test.

First load:

```
WKWebView load html time: 5.014074s

UIWebView load html time: 2.980477s
```

return to the previous page, load again:

```
WKWebView load html time: 4.379930s

UIWebView load html time: 0.028950
```

**Comment by housenkui** [comment]
<img width="1077" alt="yyy" src="https://user-images.githubusercontent.com/5885635/37640508-e6360f90-2c50-11e8-8bb8-5362ec350361.png">
Xcode 8.2 gave me an error if i use Iphone, but if i use Simulator that is ok.

what  should i do?

If i user  Xcode 9.2  that do well both in Iphone  and Simulator.

**Comment by iPermanent** [comment]
You should declare an interface by protocol at the .h file, so the xcode can recognize this. And by the way, we always use the latest version Xcode to avoid strange problems on iOS, I recommend you to do it as well.

**Comment by Prathapreddy26** [comment]
What is the purpose of this method?
- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
?
