### ISSUE TITLE
bridge.registerHandler a method but sometimes it doesn't work

### ISSUE THREAD

**Issue by mitoop** [marcuswestin/WebViewJavascriptBridge#279]
I get a problem: I use `bridge.registerHandler` register a method in Javascript,but it sometimes doesn't work. I change the image src , but the image doesn't change sometimes.  
```
 bridge.registerHandler('idCardsFrontImageUrl', function(response, responseCallback) {
      response = String(response);
      document.getElementById('app-uploader-fronts').src = response;
      document.getElementsByName('id_card_front_mark')[0].value = response;
      document.getElementById('id-photo-fronts-operate').style.display="inline";
      document.getElementById('id-photo-fronts-exist').style.display="inline";
      document.getElementById('id-photo-fronts-no-exist').style.display="none";
      document.getElementById('id-photo-fronts-progress').style.display="none";
      //responseCallback(response);
    });
```

**Comment by lokimeyburg** [comment]
```
Re: I change the image src , but the image doesn't change sometimes.
```
Are you sure this isn't a browser problem? Your Javascript looks fine to me, but I'm not sure why the image won't update. Hard to say without more details.

Can you confirm that the handler `idCardsFrontImageUrl`does in fact get called? 

```
 bridge.registerHandler('idCardsFrontImageUrl', function(response, responseCallback) {
      response = String(response);
      console.log('Yup, the handler is being called');
      document.getElementById('app-uploader-fronts').src = response;
     // ...
```

Maybe try this instead? (The code does the same thing... just shooting in the dark here with suggestions). 

```
document.getElementById('app-uploader-fronts').setAttribute('src', response);
```

**Comment by mitoop** [comment]
@lokimeyburg  It exists two same html element named `app-uploader-fronts` because of another reason. Thanks for your time.

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!
