### ISSUE TITLE
When I Use WebViewJavascriptBridge on iOS 10.2 , I get a crash

### ISSUE THREAD

**Issue by nwgdegitHub** [marcuswestin/WebViewJavascriptBridge#283]
Hi, My Friend
When I Use WebViewJavascriptBridge on iOS 10.2 , I get a crash. But it's Ok at other iOS Systems . 
this is the crash 
> 
ExampleApp-iOS(14203,0x1b4175c40) malloc: *** error for object 0x1740adaa0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Could you please hava a look at this question?

各位路过的大佬们，你们在使用的时候有遇到ios10.2WKWebView崩溃的事吗？

# WVJB Bug Report

Thanks for reporting an issue with WebViewJavascriptBridge.

### Do these 4 things and I will fix your problem!

1. Go to https://github.com/marcuswestin/WebViewJavascriptBridge and click Fork.
2. Clone your fork, `cd` into it and run `make test`. All tests should pass!
3. Edit `Tests/WebViewJavascriptBridgeTests/BridgeTests.m` and create a new, failing test which demostrates your issue.
4. Create a pull request for https://github.com/marcuswestin/WebViewJavascriptBridge

#### That's it!

I will take it from there and promise that I'll fix your problem ASAP.

#### If you don't do this then I can't help you!

And I probably won't :)

Cheers,
@marcuswestin

**Comment by nwgdegitHub** [comment]
I am sorry ,I had  solved this .
I have a reference：
[https://stackoverflow.com/questions/971249/how-to-find-the-cause-of-a-malloc-double-free-error/43885754#43885754](url)

**Comment by d553296416** [comment]
是的，遇到了

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!
