### ISSUE TITLE
Cotizaciones hoja 2

### ISSUE THREAD

**Issue by 2Contal** [marcuswestin/WebViewJavascriptBridge#286]
Buenas tardes: 

Para las cotizaciones sería ideal que puedan agregar un espacio para colocar comentarios. 
Es decir, hoja uno de valores y la hoja de 2 un espacio en blanco para colocar comentarios adicionales.  
Lo ideal que pueda tener 50 líneas esa segunda página. 

[Cotización cliente Cristal One  DEF.pdf](https://github.com/marcuswestin/WebViewJavascriptBridge/files/1015555/Cotizacion.cliente.Cristal.One.DEF.pdf)

![cotizaciones](https://cloud.githubusercontent.com/assets/28711875/26266688/74f871f6-3cb4-11e7-8cf6-18cf2a65f867.PNG)
![cotizaciones2](https://cloud.githubusercontent.com/assets/28711875/26266687/74f6eaf2-3cb4-11e7-98de-a95c1534c347.PNG)

Cualquier duda me avisan y lo vemos juntos! 

Saludos, 

Ana.

**Comment by 2Contal** [comment]
Soporte técnico: 
En el chat de clientes estaría pendiente agregar el ícono de adjunto para insertar documentos. 

![caso 1](https://cloud.githubusercontent.com/assets/28711875/26266876/4b344696-3cb5-11e7-9cd6-6ccdfa863f0f.PNG)

Saludos, 

Ana.

**Comment by 2Contal** [comment]
comentarios

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!
