### ISSUE TITLE
__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_7_1

### ISSUE THREAD

**Issue by ZanderDev** [marcuswestin/WebViewJavascriptBridge#287]
Hi, My Friend

in WKWebViewJavascriptBridge.h file

#if (__MAC_OS_X_VERSION_MAX_ALLOWED > __MAC_10_9 || __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_7_1)
#define supportsWKWebKit
#endif

it should be fixed  , because  WKWebView API_AVAILABLE(macosx(10.10), ios(8.0))

#if (__MAC_OS_X_VERSION_MAX_ALLOWED > __MAC_10_9 || __IPHONE_OS_VERSION_MAX_ALLOWED > __IPHONE_7_1)
#define supportsWKWebKit
#endif

**Comment by marcuswestin** [comment]
Please open PR with change made.

Thanks!
