### ISSUE TITLE
Dependency "WebViewJavascriptBridge" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by kepingchang** [marcuswestin/WebViewJavascriptBridge#288]
when i use Carthage.

my 'Cartfile' file:github "https://github.com/marcuswestin/WebViewJavascriptBridge"
then do"carthage update --platform ios"

Dependency "WebViewJavascriptBridge" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/marcuswestin/WebViewJavascriptBridge/issues/new

**Comment by kepingchang** [comment]
![image](https://cloud.githubusercontent.com/assets/19192660/26479760/439fc0b0-4208-11e7-863a-3c17d0fdbcef.png)
this is the picture.

**Comment by marcuswestin** [comment]
Unfortunately I know nothing about Carthage.

Sorry!

**Comment by marcuswestin** [comment]
Unfortunately I know nothing about Carthage. WVJB is working fine for people using cocapods.

Sorry!
