### ISSUE TITLE
iphone7 iOS 10.1.1 crash 

### ISSUE THREAD

**Issue by lihong-singlers** [marcuswestin/WebViewJavascriptBridge#289]
Use wkwebview, iphone 6s and kinds of Simulators  no problem ,but  iphone7 crashed. version iOS 10.1.1.  The  report is 'malloc: *** error for object 0x1700ac840: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug', I canot find the reason.

**Comment by a254711559** [comment]
YES,I also meet this problem

**Comment by d553296416** [comment]
I also meet this problem too

**Comment by Leagon** [comment]
I meet too. How to slove it?

**Comment by d553296416** [comment]
close your safari  preview can slove it.  xcode developer mode have a problem in wkwebview

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case.

Try latest WVJB version 6.0.3 and feel free to reopen if you're still having issues.

Thanks!
