### ISSUE TITLE
5.0.8 https

### ISSUE THREAD

**Issue by lemoncbc** [marcuswestin/WebViewJavascriptBridge#291]
# WVJB Bug Report

Thanks for reporting an issue with WebViewJavascriptBridge.

### Do these 4 things and I will fix your problem!

1. Go to https://github.com/marcuswestin/WebViewJavascriptBridge and click Fork.
2. Clone your fork, `cd` into it and run `make test`. All tests should pass!
3. Edit `Tests/WebViewJavascriptBridgeTests/BridgeTests.m` and create a new, failing test which demostrates your issue.
4. Create a pull request for https://github.com/marcuswestin/WebViewJavascriptBridge

#### That's it!

I will take it from there and promise that I'll fix your problem ASAP.

#### If you don't do this then I can't help you!

And I probably won't :)

Cheers,
@marcuswestin

**Comment by lemoncbc** [comment]
5.0.8版本 访问https网页时会和webBridge的协议冲突，有人遇到过吗？

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case and reopen if you're still having issues.

Thanks!
