### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by callblueday** [marcuswestin/WebViewJavascriptBridge#293]
```js
function _fetchQueue() {
  var messageQueueString = JSON.stringify(sendMessageQueue);
  sendMessageQueue = [];
  return messageQueueString;
}
```

`JSON.stringify(sendMessageQueue)` reports  error `TypeError: Converting circular structure to JSON`

**Comment by tanis2000** [comment]
You have circular references in the message you're passing over. You should make sure that you do not have any or you won't be able to serialize it

**Comment by marcuswestin** [comment]
@callblueday: this is a problem in the values you're passing to WVJB. Make sure there are no circular references in there.
