### ISSUE TITLE
when webview no DidFinishLoad,then have a problem

### ISSUE THREAD

**Issue by zjklyl931081** [marcuswestin/WebViewJavascriptBridge#294]
When making a second refresh，then, do [self _dispatchMessage:message];  
- (void)_queueMessage:(WVJBMessage*)message {
    if (self.startupMessageQueue) {
        [self.startupMessageQueue addObject:message];
    }
    else {
        [self _dispatchMessage:message];
    }
}
if webview Did not finish
- (void)webViewDidFinishLoad:(UIWebView *)webView
at this time do 
- (void) _evaluateJavascript:(NSString *)javascriptCommand {
    [self.delegate _evaluateJavascript:javascriptCommand];
}
javascript No response .

beasuse  Must be loaded 'webViewDidFinishLoad' before it can respond When executing the following code
- (NSString*) _evaluateJavascript:(NSString*)javascriptCommand {
    [_webView evaluateJavaScript:javascriptCommand completionHandler:nil];
    return NULL;
}

so how can i do that

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case and reopen if you're still having issues.

Thanks!
