### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by applejian** [marcuswestin/WebViewJavascriptBridge#301]
在我的项目里 我封装了一个组件 大致功能是 同时兼容 uiwebview 和 wkwebview，并且有网页加载的进度条，整合了WebViewJavascriptBridge，在WebViewJavascriptBridge集成这块稍微调整了下，如：（1）
ExampleApp.html 中的 那段初始化js代码 在webview加载网页的时候提前通过oc代码注入进去，好处是前端无需加那么多坨代码，（2）如果oc这边需要注册方法，在调用registerHandler前先执行这么段伪代码：
`var %@ = function %@(data, callback) {
                                                 var tmp = arguments.callee.toString();
                                                 var re = /function\\s*(\\w*)/i;
                                                 var matches = re.exec(tmp);
                                                 var methodName = matches[1];
                                                 
                                                 setupWebViewJavascriptBridge(function(bridge) {
                                                     bridge.callHandler(methodName, data, function(response){
                                                         console.log('response:'+response);
                                                         if(callback){
                                                             callback(response);
                                                         }
                                                     });
                                                 });
                                             }
                                             ;
                                             if(!bridgeCallHandler){
                                                 var bridgeCallHandler = function(methodName, data, callback){
                                                     setupWebViewJavascriptBridge(function(bridge) {
                                                         bridge.callHandler(methodName, data, callback);
                                                     });
                                                 }
                                             }`

（3）前端网页调用oc 方法的时候 只需 xxxMethodName(xxData) 或者xxxMethodName(xxData,xxCallback)，原来的setupWebViewJavascriptBridge 方式也能调用
(4) 如果前端想注册brige方法 也是可以 ，大部分 js的普通方法都已经够用了。

整理上面的原因是因为公司之前的 前端人员经常把setupWebViewJavascriptBridge 这个方法搞混乱，导致页面加载 或者初始化不成功等等，而且调用也混乱，经常出现适配了安卓苹果又不行了，整理成上面这种致使两遍都省事了许多，前端少了一段初始化的东西，很多时候前端换人，可能就漏加初始化那端js代码，导致排查问题等等

**Comment by fifyrio** [comment]
Good, then can you speak English

**Comment by marcuswestin** [comment]
Hi,

Please create a PR with a failing test case and reopen if you're still having issues.

Thanks!

**Comment by semnyqu** [comment]
你这个方案挺好的，不用让前端改动很多东西，也不用每个h5界面增加一坨js;
不过不知你是使用WKUserScript加载这段js伪代码还是其它方案；

**Comment by dustturtle** [comment]
@applejian 你的方案听起来很好，能否发我一份学习探讨一下？ openglnewbee@163.com

**Comment by taojeff** [comment]
有没有针对WK进行一定量的js注入 @applejian
