### ISSUE TITLE
crash at ios11

### ISSUE THREAD

**Issue by tospery** [marcuswestin/WebViewJavascriptBridge#315]
use WKWebview in iOS11, will crash at webView:decidePolicyForNavigationAction:decisionHandler method.
the crash reason:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[WKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'

**Comment by roMummy** [comment]
The method on lssues does not solve the problem

**Comment by marcuswestin** [comment]
Fixed in 6.0.3
