### ISSUE TITLE
wkwebview not work for iPad pro(3rth generation) in iOS 13 beta 5

### ISSUE THREAD

**Issue by WakeyWoo** [marcuswestin/WebViewJavascriptBridge#380]
wkwebview not work for iPad pro(3rth generation) in iOS 13 beta 5

in iOS 13 beta 5, the javascript callback not work for wkwebview of iPad pro(3rth generation)

**Comment by Coeur** [comment]
Does it work on UIWebView?
Do you get Xcode warnings?

**Comment by WakeyWoo** [comment]
the issue also on simulator or device of ipad pro(3rd gen), but it work on UIWebView. it build on Xcode 11 beta. simulator warnings is: "[Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT ", device warnings is: "nw_connection_receive_internal_block_invoke [C10] Receive reply failed with error "Operation canceled""

**Comment by WakeyWoo** [comment]
the issue also on simulator or device of ipad pro(3rd gen), but it work on UIWebView. it build on Xcode 11 beta. simulator warnings is: "[Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT ", device warnings is: "nw_connection_receive_internal_block_invoke [C10] Receive reply failed with error "Operation canceled""




------------------ 原始邮件 ------------------
发件人: "Antoine Cœur"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午5:04
收件人: "marcuswestin/WebViewJavascriptBridge"<WebViewJavascriptBridge@noreply.github.com>;
抄送: "Wakey Woo"<175281759@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [marcuswestin/WebViewJavascriptBridge] wkwebview not work foriPad pro(3rth generation) in iOS 13 beta 5 (#380)




Does it work on UIWebView?
 Do you get Xcode warnings?

**Comment by Coeur** [comment]
I tried with:
- the example app for iOS from master branch
- Xcode Version 11.0 beta 5 (11M382q) on Mojave
- real device iPad (5th generation) on iOS 13 beta 5

=> and it works with WKWebView.

**Comment by WakeyWoo** [comment]
I have found this issue. H5 have a restriction about navigator.userAgent, after iOS 13, iPad userAgent is Mac。

**Comment by Coeur** [comment]
@WakeyWoo, correction, I was testing on iOS 13 beta 6 (17A5556d).
=> and it works well with WKWebView on real device iPad (5th generation) on iOS 13 beta 6 (17A5556d).

**Comment by zisulu** [comment]
> �I have found this issue. H5 have a restriction about navigator.userAgent, after iOS 13, iPad userAgent is Mac。

iOS13 has added the API of WKWebpagePreferences. WKContentModeDesktop will be used by default on iPadOS. You just need to set WKWebpagePreferences to WKContentModeMobile.And then the UserAgent is perfectly normal.
