### ISSUE TITLE
iOS13 disables uiwebview, this warehouse will be rejected

### ISSUE THREAD

**Issue by postponement** [marcuswestin/WebViewJavascriptBridge#403]
A friend asked a question, and the use of uiwebView was banned in April. I saw that the file WebViewJavascriptBridge is still using uiwebView, which will cause the APP to be rejected. May the author update the file before April?

**Comment by zhangzhihua2019** [comment]
我也担心这个问题,,好像博主不维护了

**Comment by zhengjunjie11** [comment]
https://www.jianshu.com/p/4e4d937e5acb 这篇文章通过配置PodFile文件去除UIWebView

**Comment by libtinker** [comment]
> A friend asked a question, and the use of uiwebView was banned in April. I saw that the file WebViewJavascriptBridge is still using uiwebView, which will cause the APP to be rejected. May the author update the file before April?

https://www.jianshu.com/p/4e4d937e5acb 这篇文章通过配置PodFile文件去除UIWebView

**Comment by housenkui** [comment]
我已经重构了这个库.
如果您遇到麻烦，可以尝试使用它.
下载地址:
https://github.com/housenkui/JavascriptBridge
它更轻，使用更简单. 只需要一个参数就能让Xcode输出js的console.log.
10分钟之内应该可以完成接入.
