### ISSUE TITLE
提交审核被拒，因为使用了UIWebView，有办法解决吗？

### ISSUE THREAD

**Issue by Panerly** [marcuswestin/WebViewJavascriptBridge#414]
# WVJB Bug Report

Thanks for reporting an issue with WebViewJavascriptBridge.

### Do these 4 things and I will fix your problem!

1. Go to https://github.com/marcuswestin/WebViewJavascriptBridge and click Fork.
2. Clone your fork, `cd` into it and run `make test`. All tests should pass!
3. Edit `Tests/WebViewJavascriptBridgeTests/BridgeTests.m` and create a new, failing test which demostrates your issue.
4. Create a pull request for https://github.com/marcuswestin/WebViewJavascriptBridge

#### That's it!

I will take it from there and promise that I'll fix your problem ASAP.

#### If you don't do this then I can't help you!

And I probably won't :)

Cheers,
@marcuswestin

**Comment by Panerly** [comment]
提交构建版本一直被拒，经检测webviewJavaScriptBridge使用了UIWebView，请问如何更改才可以去除所有使用UIWebView的功能？

**Comment by dengxingwen** [comment]
你不用pod引入了，直接把源码下载下来，然后把这俩文件删除不就行了WebViewJavascriptBridge.h WebViewJavascriptBridge.m

**Comment by Panerly** [comment]
> 你不用pod引入了，直接把源码下载下来，然后把这俩文件删除不就行了WebViewJavascriptBridge.h WebViewJavascriptBridge.m

嗯 已经解决了

**Comment by truongluuxuan** [comment]
@Panerly can you write your WebViewJavascriptBridge.m after edit?

**Comment by pugpngying123** [comment]
大佬 我也遇到了 怎么解决呢

**Comment by tangguoan** [comment]
还是希望作者,在原先的库中处理一下,并更新pod源.

**Comment by housenkui** [comment]
我已经重构了这个库.
如果您遇到麻烦，可以尝试使用它.
下载地址:
https://github.com/housenkui/JavascriptBridge
它更轻，使用更简单. 只需要一个参数就能让Xcode输出js的console.log.
10分钟之内应该可以完成接入.

**Comment by Panerly** [comment]
> @Panerly can you write your WebViewJavascriptBridge.m after edit? "Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability." => It kill my day.

you can try this :
https://github.com/housenkui/JavascriptBridge
