### ISSUE TITLE
我已经重构了这个库，10分钟就能完成接入,也许可以帮助你.

### ISSUE THREAD

**Issue by housenkui** [marcuswestin/WebViewJavascriptBridge#426]
我已经重构了这个库，10分钟就能完成接入,也许可以帮助你.
 OC: https://github.com/SDBridge/SDBridgeOC
 Swift: https://github.com/SDBridge/SDBridgeSwift
Java: https://github.com/SDBridge/SDBridgeJava 
Kotlin: https://github.com/SDBridge/SDBridgeKotlin
而且还有h5端参考对接的Demo
https://github.com/SDBridge/TypeScriptDemo

**Comment by Meowzz95** [comment]
Shame

**Comment by marcuswestin** [comment]
Imitation is the sincerest form of flattery :)
