### ISSUE TITLE
ViewController does not dealloc when push to another view

### ISSUE THREAD

**Issue by giver** [marcuswestin/WebViewJavascriptBridge#62]
I have dealloc problem when using WVJB enable UIWebView. I think problem maybe the memory management. Right?

**Without WVJB**
A -> push -> B (UIWevView) -> pop back -> A (A trigger dealloc) -> B (UIWebView)

**With WVJB**
A -> push -> B (UIWevView) -> pop back -> A (A not trigger dealloc) -> B (UIWevView but nothing happen here)

**Without WVJB**

``` objc
_webView = [viewController webView];
[_webView setDelegate:self];
```

**With WVJB**

``` objc
 _webView = [viewController webView];
[WebViewJavascriptBridge enableLogging];
_bridge = [WebViewJavascriptBridge bridgeForWebView:_webView webViewDelegate:self handler:^(id data, WVJBResponseCallback responseCallback) {
    NSLog(@"ObjC received message from JS: %@", data);
    responseCallback(@"Response for message from ObjC");
}];
```

**Comment by cyqluowang** [comment]
hi ,i meet the same question,if viewDidDisappear do this ,it will be reload (background ---> fo);how can i do?

**Comment by cyqluowang** [comment]
#135

**Comment by brownfeng** [comment]
I have meet the same problem, I find a way to release the ViewController by setting bridge to nil when call `popViewController` and use weakSelf in the bridge blocks at the same time.
