### ISSUE TITLE
Porting to WKWebView

### ISSUE THREAD

**Issue by sohocoke** [marcuswestin/WebViewJavascriptBridge#84]
It was good to work with WVJsBrige as a component for fluid interop between native and web code. I'd love to continue using WKWebView as I port the reference WebView-based app framework for our products and client projects.

Until 10.10 becomes stable enough to develop in, we can use the iOS 8 SDK to start working on a port. I'd like to start one soon, and would love to hear from you regarding how you'd plan out an attack. Any feedback or advice would be welcome here.

**Comment by erdemgc** [comment]
i have used the WKWebView version of WebViewJavascriptBridge. It seems it takes messages from web source, but does not proceed to next page , it just stays. What might be the wrong? Does anyone have the same issue?

**Comment by lokimeyburg** [comment]
Hey, I'll take a look and see if I can repro. It works for you on the 'master' branch though, right?

**Comment by lokimeyburg** [comment]
@erdemgc Hey I just tried it out and I couldn't repro. Here's a screen-cap of me navigating to a new page and sending messages back-and-forth: http://cloud.loki.io/0c2K2B1s0N29

If you're still having problems, I suggest opening up a new issue with more information on how we can reproduce your bug.

**Comment by marcuswestin** [comment]
This is done since a while back :)

Use 4.1.5 for WKWebView support.

You should also consider switching to v5.0.1. If you do, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage.

Cheers!

**Comment by laraibmalik90** [comment]
Hey I am using WKweview for loading request, I want to store data content and load it to ukwebview when internet is not available , Is that possible, Can anyone help on how to implement that?
